- .github/workflows/integration_tests.yml
- ixdiagnose/plugins/active_directory.py
- ixdiagnose/plugins/base.py
- ixdiagnose/test/pytest/integration/test_artifacts.py
- ixdiagnose/test/pytest/integration/test_plugins.py
- ixdiagnose/test/pytest/integration/utils.py
- requirements.txt
Integration tests have been added to validate 2 parts of ixdiagnose:
1. plugins
2. artifacts
(1) will validate that all plugins are executed and their report is appropriately generated whilst also making sure that all metrics in a plugin are executed with their report generated.
(2) will validate that all artifacts are gathered and their report is appropriately generated whilst also making sure that all items in an artifact are gathered with their report generated.
> Integration tests for ixdiagnose

- ixdiagnose/test/pytest/unit/event/test_event.py
Unit tests have been added to validate that callback specified has correct format and that clearing any registered callbacks works as intended.
> Unit test for callback consumption

- ixdiagnose/config.py
- ixdiagnose/plugin.py
- ixdiagnose/plugins/base.py
We have `Configuration` class which held logic for setting user specified values or sane defaults which defined how `ixdiagnose` got executed. The same model has been extended to allow other configuration knobs which can be used to control behaviour of debug generation.
Motivation behind the singleton pattern is that the `conf` can be consumed directly when consuming `ixdiagnose` as a python library and the same can be consumed when CLI settings are applied making it generic enough to handle both cases.
Configuration knobs have been extended to allow for certain requests which were desired in the re-write of the debug generation tool.
> Extend the configuration model to be able to change behaviour of debug generation

- ixdiagnose/plugin.py
`conf` object is re-initialised in the process pool which results in various inconsistencies when executing plugins.
We could workaround it but after discussion with @yocalebo we decided to remove the process pool executor for now and re-visit this as required.
> NAS-121523 / 23.10 / Remove process pool executor when gathering plugins data

- .github/codecov.yml
- .github/workflows/test_coverage.yml
- ixdiagnose/test/pytest/unit/metrics/test_command_metric.py
- ixdiagnose/test/pytest/unit/metrics/test_directory_tree_metric.py
- ixdiagnose/test/pytest/unit/metrics/test_metric.py
- ixdiagnose/test/pytest/unit/plugins/assets/smb_shares_output.txt
- ixdiagnose/test/pytest/unit/plugins/test_base_plugin.py
- ixdiagnose/test/pytest/unit/plugins/test_smart_output.py
- ixdiagnose/test/pytest/unit/plugins/test_smb_shares.py
Pytest coverage has been added to expand the scope of the testing in place for ixdiagnose and more tests have been added based on the report generated by pytest coverage to cover areas which lacked enough tests and push the coverage to 90%+.
> NAS-121554 / 23.10 / Add pytest coverage

- debian/rules
Test suite is executed when building debian package in our scale builder and we were missing pytest build time dependencies.
Add required pytest python debian packages as build time dependencies for the scale builder to successfully build ixdiagnose.
> NAS-121572 / 23.10 / Add pytest dependency to debian package

- ixdiagnose/artifacts/items/pattern.py
In `Pattern` item, `File/Directory` items were getting re-used i.e not being re-initialised properly which resulted it in accessing older closed file descriptors which were obviously closed and malformed.
Properly make sure that pattern variables are re-initialised each time it is executed again.
**Note:** This applies to both root/non-root users
> NAS-122168 / 23.10 / Fix pattern item variables

- ixdiagnose/artifacts/items/file.py
We don't need to os.fdopen() in order to fstat() an open file. It's probably a good idea to set the value of fd to -1 (bad fd) after closing it to protect against possibility of closing same fd twice (even though bug where this was happening has already been fixed). On a busy system the fd number may be reused rather quickly resulting in inexplicable errors, so let's protect against this here.
> NAS-122225 / 23.10 / Remove unnecessary os.fdopen call

- ixdiagnose/test/pytest/integration/test_plugins.py
Metrics can fail for various reasons and that will result in `metric_report` attribute being `null`.
We still get the complete traceback for the issue
```
"time_info": {
"execution_time": 0.005153656005859375,
"metric_report": null,
"metric_execution_error": "[Errno 2] No such file or directory: 'chronycs'",
"metric_execution_traceback": "Traceback (most recent call last):\n  File \"/root/ixdiagnose/ixdiagnose/plugins/base.py\", line 57, in execute_impl\n    metric_report, metric_output = metric.execute(context)  # execution mechanism TBD\n                                   ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/ixdiagnose/ixdiagnose/plugins/metrics/base.py\", line 32, in execute\n    data = self.execute_impl()\n           ^^^^^^^^^^^^^^^^^^^\n  File …
```
> NAS-122847 / 23.10 / Fix integration test when metric fails

- ixdiagnose/plugins/system.py
We switched from using `ntp` to `chrony` in NAS-117546
`ixdiagnose` requires a corresponding update.
> NAS-122842 / 23.10 / Update ixdiagnose to use chronyc rather than ntpq

- .github/workflows/ci.yml
- .github/workflows/integration_tests.yml
- .github/workflows/unittests.yml
The image `ghcr.io/truenas/ixdiagnose:master` is not being updated regularly which can result in packages missing and CI failing.
So we should be using `ghcr.io/truenas/middleware:master` instead and we are already installing the checked out ixdiagnose changes so that suffices and we don't need to maintain an updated docker image of `truenas/ixdiagnose`.
> NAS-122848 / 23.10 / Use middleware image for github CI

- ixdiagnose/plugins/factory.py
- ixdiagnose/plugins/reporting.py
It is useful to know what graphs are being recognized by netdata/reporting plugin and what identifiers it is reporting for various graphs so we can efficiently diagnose if there is a bug/mistake on middleware side.
Original PR: https://github.com/truenas/ixdiagnose/pull/32
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123401
> NAS-123401 / 23.10-BETA.1 / Get reporting debug (by Qubad786)

- ixdiagnose/plugins/zfs.py
`dataset_list.txt` had an incorrect header saying that the content refers to ZFS pools whereas it in reality points to ZFS datasets.
Update the header to appropriately refer to data which it points to.
> NAS-123567 / 24.04 / Fix dataset_list header

- ixdiagnose/plugins/zfs.py
`dataset_list.txt` had an incorrect header saying that the content refers to ZFS pools whereas it in reality points to ZFS datasets.
Update the header to appropriately refer to data which it points to.
Original PR: https://github.com/truenas/ixdiagnose/pull/38
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123567
> NAS-123567 / 23.10 / Fix dataset_list header (by Qubad786)

- ixdiagnose/plugins/zfs.py
Currently, our method for retrieving ZFS dataset properties indiscriminately fetches data for both datasets and their associated snapshots. In environments with significant snapshot usage, this approach can result in retrieving vast amounts of data. Given that users can possess thousands of snapshots, this operation becomes highly expensive and can lead to considerable performance degradation.
We've implemented a custom script that refines the data retrieval process. This script is tailored to concentrate solely on datasets, effectively excluding snapshots from the data retrieval process. By doing so, we significantly reduce the overhead and ensure a more efficient and faster operation, especially in ZFS setups with a high number of snapshots.
> NAS-123566 / 24.04 / Don't get zfs snapshots details

- ixdiagnose/plugins/zfs.py
Currently, our method for retrieving ZFS dataset properties indiscriminately fetches data for both datasets and their associated snapshots. In environments with significant snapshot usage, this approach can result in retrieving vast amounts of data. Given that users can possess thousands of snapshots, this operation becomes highly expensive and can lead to considerable performance degradation.
We've implemented a custom script that refines the data retrieval process. This script is tailored to concentrate solely on datasets, effectively excluding snapshots from the data retrieval process. By doing so, we significantly reduce the overhead and ensure a more efficient and faster operation, especially in ZFS setups with a high number of snapshots.
Original PR: …
> NAS-123566 / 23.10 / Don't get zfs snapshots details (by Qubad786)

- ixdiagnose/plugins/prerequisites/__init__.py
- ixdiagnose/plugins/prerequisites/vm.py
- ixdiagnose/plugins/vm.py
Our VM plugin is designed in such a way that calling essentially any endpoint will produce log spam in middlewared.log
```
[2023/08/17 04:46:41] (ERROR) middlewared.wait_for_libvirtd():33 - Failed to setup libvirt
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/middlewared/plugins/vm/lifecycle.py", line 25, in wait_for_libvirtd
self._system_supports_virtualization()
File "/usr/lib/python3/dist-packages/middlewared/plugins/vm/connection.py", line 61, in _system_supports_virtualization
raise CallError('This system does not support virtualization.')
middlewared.service_exception.CallError: [EFAULT] This system does not support virtualization.
```
This adds a prerequisite so that the VM plugin doesn't try and run any of these commands unless the host supports it.
> NAS-123590 / 24.04 / add VMPrerequisite to prevent log spam

- ixdiagnose/plugins/prerequisites/__init__.py
- ixdiagnose/plugins/prerequisites/vm.py
- ixdiagnose/plugins/vm.py
Our VM plugin is designed in such a way that calling essentially any endpoint will produce log spam in middlewared.log
```
[2023/08/17 04:46:41] (ERROR) middlewared.wait_for_libvirtd():33 - Failed to setup libvirt
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/middlewared/plugins/vm/lifecycle.py", line 25, in wait_for_libvirtd
self._system_supports_virtualization()
File "/usr/lib/python3/dist-packages/middlewared/plugins/vm/connection.py", line 61, in _system_supports_virtualization
raise CallError('This system does not support virtualization.')
middlewared.service_exception.CallError: [EFAULT] This system does not support virtualization.
```
This adds a prerequisite so that the VM plugin doesn't try and run any of these commands unless the host supports it. …
> NAS-123590 / 23.10 / add VMPrerequisite to prevent log spam (by yocalebo)

- ixdiagnose/plugins/prerequisites/vm.py
Function `evaluate_impl` returns `bool` but in VM prerequisite it is returning `MiddlewareResponse` object which will always evaluate to true.
Properly reference the output received from middleware for VMs being supported.
> NAS-123595 / 24.04 / Fix VMPrerequisite

- ixdiagnose/plugins/prerequisites/vm.py
Function `evaluate_impl` returns `bool` but in VM prerequisite it is returning `MiddlewareResponse` object which will always evaluate to true.
Properly reference the output received from middleware for VMs being supported.
Original PR: https://github.com/truenas/ixdiagnose/pull/48
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123595
> NAS-123595 / 23.10 / Fix VMPrerequisite (by Qubad786)

- ixdiagnose/plugins/system.py
For better readability it was requested to move `top` output command to it's own separate file.
> NAS-123643 / 24.04 / Add top output to separate file

- ixdiagnose/plugins/system.py
For better readability it was requested to move `top` output command to it's own separate file.
Original PR: https://github.com/truenas/ixdiagnose/pull/51
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123643
> NAS-123643 / 23.10 / Add top output to separate file (by Qubad786)

- ixdiagnose/plugins/factory.py
- ixdiagnose/plugins/jobs.py
This is pertinent for gathering collateral, for example, from our "tasks" and their respective results.
> NAS-123827 / 24.04 / add core.get_jobs to plugins

- ixdiagnose/plugins/system.py
This is already available in jobs plugin.
> NAS-124249 / 24.04 / Remove core.get_jobs from system plugin

- ixdiagnose/plugins/system.py
This is already available in jobs plugin.
Original PR: https://github.com/truenas/ixdiagnose/pull/68
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124249
> NAS-124249 / 23.10 / Remove core.get_jobs from system plugin (by william-gr)

- ixdiagnose/plugins/network.py
Adding a 2nd `-s` also reports the error statistics for the network interfaces. This has proven to be useful information on a customer system.
> NAS-124274 / 24.04 / add 2nd -s to show interface errors

- ixdiagnose/plugins/network.py
Adding a 2nd `-s` also reports the error statistics for the network interfaces. This has proven to be useful information on a customer system.
Original PR: https://github.com/truenas/ixdiagnose/pull/76
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124274
> NAS-124274 / 23.10 / add 2nd -s to show interface errors (by yocalebo)

- ixdiagnose/plugins/nfs.py
Add a text file, nfs-client-counts.txt, which displays the number of current NFS clients by type.
The types are: NFSv3, NFSv4.2, NFSv4.1 and NFS4.0
> NAS-124407 / 24.04 / Add text file with number of NFS clients by type

- ixdiagnose/plugins/nfs.py
Add a text file, nfs-client-counts.txt, which displays the number of current NFS clients by type.
The types are: NFSv3, NFSv4.2, NFSv4.1 and NFS4.0
Original PR: https://github.com/truenas/ixdiagnose/pull/83
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124407
> NAS-124407 / 23.10 / Add text file with number of NFS clients by type (by mgrimesix)

- ixdiagnose/plugins/vm.py
HAProxy was removed in DragonFish so there is no reason to capture it's contents in debug.
This PR removes the HAProxy related info gathering in VM plugin.
> NAS-124262 / 24.04 / Remove haproxy from ixdiagnose

- ixdiagnose/plugins/vm.py
- ixdiagnose/test/pytest/unit/test_formatter/test_formatter.py
- ixdiagnose/utils/formatter.py
This PR addresses a security concern where VM passwords are exposed in debug logs.
Applied changes remove the password key from both **vm.query** and **vm.device.query** outputs.
> NAS-124248 / 24.04 / Remove password key when retrieving VM devices details

- ixdiagnose/plugins/vm.py
- ixdiagnose/test/pytest/unit/test_formatter/test_formatter.py
- ixdiagnose/utils/formatter.py
This PR addresses a security concern where VM passwords are exposed in debug logs.
Applied changes remove the password key from both **vm.query** and **vm.device.query** outputs. 
Original PR: https://github.com/truenas/ixdiagnose/pull/82
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124248
> NAS-124248 / 23.10 / Remove password key when retrieving VM devices details (by Qubad786)

- ixdiagnose/artifacts/items/__init__.py
- ixdiagnose/artifacts/items/glob.py
- ixdiagnose/test/pytest/integration/items/test_glob.py
It was requested that we have the feature to allow specifying a glob pattern to copy over artifacts and relevant changes have been made to introduce this functionality. To consume this functionality, following diff can be applied to make use of this:
```
diff --git a/ixdiagnose/artifacts/logs.py b/ixdiagnose/artifacts/logs.py
index b49fb2e..a55deb1 100644
--- a/ixdiagnose/artifacts/logs.py
+++ b/ixdiagnose/artifacts/logs.py
@@ -1,5 +1,5 @@
from .base import Artifact
-from .items import Directory, File, Pattern
+from .items import Directory, File, Glob, Pattern
class Logs(Artifact):
@@ -25,4 +25,5 @@ class Logs(Artifact):
Pattern('fenced.+'),
Pattern('middlewared.+'),
Pattern('zettarepl.+'),
+        Glob('/sys/module/*/parameters/*'),
]
```
> NAS-124303 / 24.04 / Add glob based item to collect artifacts

- ixdiagnose/artifacts/items/__init__.py
- ixdiagnose/artifacts/items/glob.py
- ixdiagnose/test/pytest/integration/items/test_glob.py
It was requested that we have the feature to allow specifying a glob pattern to copy over artifacts and relevant changes have been made to introduce this functionality. To consume this functionality, following diff can be applied to make use of this:
```
diff --git a/ixdiagnose/artifacts/logs.py b/ixdiagnose/artifacts/logs.py
index b49fb2e..a55deb1 100644
--- a/ixdiagnose/artifacts/logs.py
+++ b/ixdiagnose/artifacts/logs.py
@@ -1,5 +1,5 @@
from .base import Artifact
-from .items import Directory, File, Pattern
+from .items import Directory, File, Glob, Pattern
class Logs(Artifact):
@@ -25,4 +25,5 @@ class Logs(Artifact):
Pattern('fenced.+'),
Pattern('middlewared.+'),
Pattern('zettarepl.+'),
+        Glob('/sys/module/*/parameters/*'),
]
```
Original PR: …
> NAS-124303 / 23.10.0 / Add glob based item to collect artifacts (by Qubad786)

- ixdiagnose/artifacts/items/__init__.py
- ixdiagnose/artifacts/items/glob.py
- ixdiagnose/test/pytest/integration/items/test_glob.py
It was requested that we have the feature to allow specifying a glob pattern to copy over artifacts and relevant changes have been made to introduce this functionality. To consume this functionality, following diff can be applied to make use of this:
```
diff --git a/ixdiagnose/artifacts/logs.py b/ixdiagnose/artifacts/logs.py
index b49fb2e..a55deb1 100644
--- a/ixdiagnose/artifacts/logs.py
+++ b/ixdiagnose/artifacts/logs.py
@@ -1,5 +1,5 @@
from .base import Artifact
-from .items import Directory, File, Pattern
+from .items import Directory, File, Glob, Pattern
class Logs(Artifact):
@@ -25,4 +25,5 @@ class Logs(Artifact):
Pattern('fenced.+'),
Pattern('middlewared.+'),
Pattern('zettarepl.+'),
+        Glob('/sys/module/*/parameters/*'),
]
```
Original PR: …
> NAS-124303 / 23.10.1 / Add glob based item to collect artifacts (by Qubad786)

- docs/build.md
- docs/cli.md
This PR adds concise Markdown documentation for the **ixdiagnose** CLI tool, providing users with clear running instructions, command options and details.
Original PR: https://github.com/truenas/ixdiagnose/pull/87
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124495
> NAS-124495 / 23.10.1 / Add CLI docs for ixdiagnose (by Qubad786)

- docs/build.md
- docs/cli.md
This PR adds concise Markdown documentation for the **ixdiagnose** CLI tool, providing users with clear running instructions, command options and details.
Original PR: https://github.com/truenas/ixdiagnose/pull/87
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124495
> NAS-124495 / 23.10.0 / Add CLI docs for ixdiagnose (by Qubad786)

- ixdiagnose/artifacts/factory.py
- ixdiagnose/artifacts/sys_parameters.py
git cherry-pick -x 80f8969851ecde1482406f0f444b8cf055fc8278
git cherry-pick -x 16e445162d0979b7fff7c42b0fe5c283ad3756bd
It was requested that we retrieve sysfs module parameters in our debug for debugging purposes.
Original PR: https://github.com/truenas/ixdiagnose/pull/96
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124597
> NAS-124597 / 23.10.0 / Collect sysfs modules parameters (by Qubad786)

- ixdiagnose/artifacts/factory.py
- ixdiagnose/artifacts/sys_parameters.py
git cherry-pick -x 80f8969851ecde1482406f0f444b8cf055fc8278
git cherry-pick -x 16e445162d0979b7fff7c42b0fe5c283ad3756bd
It was requested that we retrieve sysfs module parameters in our debug for debugging purposes.
Original PR: https://github.com/truenas/ixdiagnose/pull/96
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124597
> NAS-124597 / 23.10.1 / Collect sysfs modules parameters (by Qubad786)

- ixdiagnose/run.py
- ixdiagnose/test/pytest/unit/run/test_debug.py
Whenever we create debug directory - we set it's permissions to `0o700` so other users cannot have access to the debug as it can contain sensitive information.
> NAS-124585 / 24.04 / Make sure we set correct perms to prevent access

- ixdiagnose/run.py
- ixdiagnose/test/pytest/unit/run/test_debug.py
Whenever we create debug directory - we set it's permissions to `0o700` so other users cannot have access to the debug as it can contain sensitive information.
Original PR: https://github.com/truenas/ixdiagnose/pull/99
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124585
> NAS-124585 / 23.10.0 / Make sure we set correct perms to prevent access (by Qubad786)

- ixdiagnose/run.py
- ixdiagnose/test/pytest/unit/run/test_debug.py
Whenever we create debug directory - we set it's permissions to `0o700` so other users cannot have access to the debug as it can contain sensitive information.
Original PR: https://github.com/truenas/ixdiagnose/pull/99
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124585
> NAS-124585 / 23.10.1 / Make sure we set correct perms to prevent access (by Qubad786)

- ixdiagnose/plugins/iscsi.py
When examining a Bug Report noticed that several aspects of iSCSI configuration were missing from _iscsi_conf.json_.  Add them.
> Save additional iSCSI configuration

- ixdiagnose/plugins/iscsi.py
When examining a Bug Report noticed that several aspects of iSCSI configuration were missing from _iscsi_conf.json_.  Add them.
Original PR: https://github.com/truenas/ixdiagnose/pull/102
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124706
> NAS-124706 / 23.10.1 / Save additional iSCSI configuration (by bmeagherix)

- ixdiagnose/plugins/iscsi.py
When examining a Bug Report noticed that several aspects of iSCSI configuration were missing from _iscsi_conf.json_.  Add them.
Original PR: https://github.com/truenas/ixdiagnose/pull/102
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124706
Original PR: https://github.com/truenas/ixdiagnose/pull/103
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124706
> NAS-124706 / 23.10.0 / Save additional iSCSI configuration (by bmeagherix) (by bugclerk)

- ixdiagnose/test/pytest/integration/test_compress_debug.py
PR adds integration test to ensure that the permissions of the debug and compress paths are always set to 700.
Work was done in [this PR](https://github.com/truenas/ixdiagnose/pull/99).
> NAS-125087 / 24.04 / Add integration test for debug and compress path permissions

- ixdiagnose/test/pytest/integration/test_compress_debug.py
PR adds integration test to ensure that the permissions of the debug and compress paths are always set to 700.
Work was done in [this PR](https://github.com/truenas/ixdiagnose/pull/99).
Original PR: https://github.com/truenas/ixdiagnose/pull/117
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125087
> NAS-125087 / 23.10.1 / Add integration test for debug and compress path permissions (by Qubad786)

- ixdiagnose/artifacts/logs.py
It is useful to have netdata logs in the debug as well so we can see why netdata might be behaving weirdly.
Original PR: https://github.com/truenas/ixdiagnose/pull/116
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125086
> NAS-125086 / 23.10.1 / Grab netdata logs in debug (by Qubad786)

- ixdiagnose/plugins/hardware.py
It has been requested that we include `enclosure2.query` output to our debug as it's being used in our middleware stack and can help in potentially debugging problems.
> NAS-125815 / 24.04 / Add enclosure2 query output to debug

- ixdiagnose/plugins/hardware.py
It has been requested that we include `enclosure2.query` output to our debug as it's being used in our middleware stack and can help in potentially debugging problems.
Original PR: https://github.com/truenas/ixdiagnose/pull/139
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125815
> NAS-125815 / 23.10.2 / Add enclosure2 query output to debug (by Qubad786)

- ixdiagnose/plugins/factory.py
- ixdiagnose/plugins/rbac.py
This commit adds new plugin to include privilege-related info in debug files.
Original PR: https://github.com/truenas/ixdiagnose/pull/136
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125872
> NAS-125872 / 23.10.2 / Add plugin for privilege-related info (by anodos325)

- ixdiagnose/plugins/rbac.py
In some cases users may disable password-based authentication for root account on NAS without providing alternative administrative account. In this situation we need to perform password validation internally in middleware (and not go through PAM). Since this impacts authentication and authorization we should flag it in the debug.
> NAS-125923 / 24.04 / Add root password disabled override info to debug

- ixdiagnose/plugins/rbac.py
In some cases users may disable password-based authentication for root account on NAS without providing alternative administrative account. In this situation we need to perform password validation internally in middleware (and not go through PAM). Since this impacts authentication and authorization we should flag it in the debug.
Original PR: https://github.com/truenas/ixdiagnose/pull/141
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125923
> NAS-125923 / 23.10.2 / Add root password disabled override info to debug (by anodos325)

- ixdiagnose/artifacts/items/directory.py
- ixdiagnose/artifacts/proc.py
- ixdiagnose/test/pytest/integration/test_artifacts.py
Users were having large `dbufs` files which were expensive to query. 
This PR adds the functionality to skip copying files and / or directories in artifacts' directory class.
Skips capturing the `/proc/spl/kstat/zfs/dbufs` file in debug to prevent unnecessary resource utilization.
> NAS-126012 / 24.04 / Add ability to ignore files/dirs for directory item

- ixdiagnose/artifacts/items/directory.py
- ixdiagnose/artifacts/proc.py
- ixdiagnose/test/pytest/integration/test_artifacts.py
Users were having large `dbufs` files which were expensive to query. 
This PR adds the functionality to skip copying files and / or directories in artifacts' directory class.
Skips capturing the `/proc/spl/kstat/zfs/dbufs` file in debug to prevent unnecessary resource utilization.
Original PR: https://github.com/truenas/ixdiagnose/pull/148
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126012
> NAS-126012 / 23.10.2 / Add ability to ignore files/dirs for directory item (by Qubad786)

- ixdiagnose/plugins/active_directory.py
We were missing kerberos information here.
Original PR: https://github.com/truenas/ixdiagnose/pull/153
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126889
> NAS-126889 / 23.10.2 / Add missing information to AD debug (by anodos325)

- ixdiagnose/plugins/active_directory.py
We were missing kerberos information here.
Original PR: https://github.com/truenas/ixdiagnose/pull/153
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126889
> NAS-126889 / 24.04-RC.1 / Add missing information to AD debug (by anodos325)

- ixdiagnose/plugins/active_directory.py
We were missing kerberos information here.
Original PR: https://github.com/truenas/ixdiagnose/pull/153
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126889
> NAS-126889 / 24.04-BETA.1 / Add missing information to AD debug (by anodos325)

- ixdiagnose/artifacts/items/directory.py
- ixdiagnose/artifacts/proc.py
- ixdiagnose/test/pytest/integration/test_artifacts.py
Change adds /proc/net/bonding dir in debug to give visibility for configured bonds. Also PR fixes default value handling of `ignore_items` of Directory class and adds integration test.
> NAS-126908 / 24.10 / Add /proc/net/bonding dir to debug

- ixdiagnose/plugins/factory.py
- ixdiagnose/plugins/failover.py
This PR adds middleware command output of `failover.config` to debug's network plugin enabling visibility into network timeout settings specifically. 
Original PR: https://github.com/truenas/ixdiagnose/pull/157
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126910
> NAS-126910 / 23.10.2 / Grab failover config in debug (by Qubad786)

- ixdiagnose/plugins/factory.py
- ixdiagnose/plugins/failover.py
This PR adds middleware command output of `failover.config` to debug's network plugin enabling visibility into network timeout settings specifically. 
Original PR: https://github.com/truenas/ixdiagnose/pull/157
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126910
> NAS-126910 / 24.04-RC.1 / Grab failover config in debug (by Qubad786)

- ixdiagnose/artifacts/items/directory.py
- ixdiagnose/artifacts/proc.py
- ixdiagnose/test/pytest/integration/test_artifacts.py
Change adds /proc/net/bonding dir in debug to give visibility for configured bonds. Also PR fixes default value handling of `ignore_items` of Directory class and adds integration test.
Original PR: https://github.com/truenas/ixdiagnose/pull/158
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126908
> NAS-126908 / 23.10.2 / Add /proc/net/bonding dir to debug (by Qubad786)

- ixdiagnose/artifacts/items/directory.py
- ixdiagnose/artifacts/proc.py
- ixdiagnose/test/pytest/integration/test_artifacts.py
Change adds /proc/net/bonding dir in debug to give visibility for configured bonds. Also PR fixes default value handling of `ignore_items` of Directory class and adds integration test.
Original PR: https://github.com/truenas/ixdiagnose/pull/158
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126908
> NAS-126908 / 24.04-RC.1 / Add /proc/net/bonding dir to debug (by Qubad786)

- ixdiagnose/plugins/kubernetes.py
This commit adds changes to not retrieve app's history in debug as it's not really useful and can be asked for later explicitly if required which would be quite rare. Secondly app's history has config of user which can contain sensitive information - it cannot be managed in the schema of app's but can be managed here, however seeing that retrieving history has little to no utility, let's remove it from debug.
> NAS-126925 / 24.10 / Do not retrieve app's history in debug

- ixdiagnose/plugins/kubernetes.py
This commit adds changes to not retrieve app's history in debug as it's not really useful and can be asked for later explicitly if required which would be quite rare. Secondly app's history has config of user which can contain sensitive information - it cannot be managed in the schema of app's but can be managed here, however seeing that retrieving history has little to no utility, let's remove it from debug.
Original PR: https://github.com/truenas/ixdiagnose/pull/163
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126925
> NAS-126925 / 23.10.2 / Do not retrieve app's history in debug (by sonicaj)

- ixdiagnose/plugins/kubernetes.py
This commit adds changes to not retrieve app's history in debug as it's not really useful and can be asked for later explicitly if required which would be quite rare. Secondly app's history has config of user which can contain sensitive information - it cannot be managed in the schema of app's but can be managed here, however seeing that retrieving history has little to no utility, let's remove it from debug.
Original PR: https://github.com/truenas/ixdiagnose/pull/163
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126925
> NAS-126925 / 24.04-RC.1 / Do not retrieve app's history in debug (by sonicaj)

- ixdiagnose/plugins/failover.py
- ixdiagnose/plugins/prerequisites/__init__.py
- ixdiagnose/plugins/prerequisites/active_directory.py
- ixdiagnose/plugins/prerequisites/failover.py
- ixdiagnose/plugins/prerequisites/vm.py
Add a `FailoverPrerequisite` class and add more failover specific data to the failover plugin.
Original PR: https://github.com/truenas/ixdiagnose/pull/168
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127353
> NAS-127353 / 24.04-RC.1 / More failover info (by yocalebo)

- ixdiagnose/artifacts/base.py
- ixdiagnose/artifacts/items/__init__.py
- ixdiagnose/artifacts/items/base.py
- ixdiagnose/artifacts/items/pattern.py
- ixdiagnose/artifacts/logs.py
- ixdiagnose/test/pytest/integration/items/test_directory_pattern.py
- ixdiagnose/test/pytest/integration/test_artifacts.py
We had Directory type items in artifacts for which size check from `individual_item_max_size_limit` was applied to whole of directory instead of each file / subfolder of dir. That was because the above variable is not configurable at `item` level but rather `artifact` level where it sets the limit for each item in the artifact where a directory type would be 1 item.
So whenever there was a case when any subfolder crosses the size limit, the whole of dir was skipped like in case of `samba4` dir.
Added DirectoryPattern as a new item type with the default pattern `.*` which copies complete directory just like Directory item type but applies size check on subfolders and files of the dir like Pattern item type and additionally filters can be applied as well if we want to be selective about the …
> NAS-127445 / 24.10 / Make sure we capture samba log directories

- ixdiagnose/artifacts/base.py
- ixdiagnose/artifacts/items/__init__.py
- ixdiagnose/artifacts/items/base.py
- ixdiagnose/artifacts/items/pattern.py
- ixdiagnose/artifacts/logs.py
- ixdiagnose/test/pytest/integration/items/test_directory_pattern.py
- ixdiagnose/test/pytest/integration/test_artifacts.py
We had Directory type items in artifacts for which size check from `individual_item_max_size_limit` was applied to whole of directory instead of each file / subfolder of dir. That was because the above variable is not configurable at `item` level but rather `artifact` level where it sets the limit for each item in the artifact where a directory type would be 1 item.
So whenever there was a case when any subfolder crosses the size limit, the whole of dir was skipped like in case of `samba4` dir.
Added DirectoryPattern as a new item type with the default pattern `.*` which copies complete directory just like Directory item type but applies size check on subfolders and files of the dir like Pattern item type and additionally filters can be applied as well if we want to be selective about the …
> NAS-127445 / 23.10.3 / Make sure we capture samba log directories (by Qubad786)

- ixdiagnose/artifacts/base.py
- ixdiagnose/artifacts/items/__init__.py
- ixdiagnose/artifacts/items/base.py
- ixdiagnose/artifacts/items/pattern.py
- ixdiagnose/artifacts/logs.py
- ixdiagnose/test/pytest/integration/items/test_directory_pattern.py
- ixdiagnose/test/pytest/integration/test_artifacts.py
We had Directory type items in artifacts for which size check from `individual_item_max_size_limit` was applied to whole of directory instead of each file / subfolder of dir. That was because the above variable is not configurable at `item` level but rather `artifact` level where it sets the limit for each item in the artifact where a directory type would be 1 item.
So whenever there was a case when any subfolder crosses the size limit, the whole of dir was skipped like in case of `samba4` dir.
Added DirectoryPattern as a new item type with the default pattern `.*` which copies complete directory just like Directory item type but applies size check on subfolders and files of the dir like Pattern item type and additionally filters can be applied as well if we want to be selective about the …
> NAS-127445 / 24.04.0 / Make sure we capture samba log directories (by Qubad786)

- ixdiagnose/artifacts/logs.py
Corresponding middlewared PR #[13395 ](https://github.com/truenas/middleware/pull/13395) has been merged.
> NAS-127340 / 24.10 / Move scst logs into /var/log/scst.log

- ixdiagnose/plugins/system_state.py
We are not currently retrieving bootenv details in debug and we need to manually examine different sections in debug to determine that, so adding that relevant information in the debug.
> NAS-128061 / 24.10 / Retrieve bootenv details in debug

- ixdiagnose/plugins/system_state.py
We are not currently retrieving bootenv details in debug and we need to manually examine different sections in debug to determine that, so adding that relevant information in the debug.
Original PR: https://github.com/truenas/ixdiagnose/pull/176
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128061
> NAS-128061 / 24.04.0 / Retrieve bootenv details in debug (by Qubad786)

- ixdiagnose/plugins/kubernetes.py
PR adds the change to retrieve memory, network, etc stats in `chart.release.query` improving visibility
> NAS-128134 / 24.10 / Get chart release stats in debug

- ixdiagnose/plugins/factory.py
- ixdiagnose/plugins/ups.py
PR adds a new plugin to include output of upsc command to debug files if ups service is running for better visibility of what's going on in their UPS parameters.
Original PR: https://github.com/truenas/ixdiagnose/pull/180
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128135
> NAS-128135 / 24.04.0 / Add UPS plugin (by Qubad786)

- ixdiagnose/plugins/system.py
Change adds the system global ID to system info in system plugin. The change will help in uniquely identifying the systems.
> NAS-123519 / 24.10 / Add system global ID to debug

- ixdiagnose/plugins/system_state.py
This file is of critical importance since it will store the error message that is received during an alembic migration during upgrades.
> NAS-128223 / 24.10 / add /data/update.failed

- ixdiagnose/plugins/system_state.py
This file is of critical importance since it will store the error message that is received during an alembic migration during upgrades.
Original PR: https://github.com/truenas/ixdiagnose/pull/183
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128223
> NAS-128223 / 24.04.0 / add /data/update.failed (by yocalebo)

- ixdiagnose/plugins/system_state.py
This file is of critical importance since it will store the error message that is received during an alembic migration during upgrades.
Original PR: https://github.com/truenas/ixdiagnose/pull/183
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128223
> NAS-128223 / 24.04.1 / add /data/update.failed (by yocalebo)

- ixdiagnose/plugins/system.py
This endpoint has been renamed in middleware and it's usages need to be covered.
> NAS-127150 / 24.10 / Cover up usages of truecommand.connected endpoint

- ixdiagnose/artifacts/logs.py
This commit adds changes to ensure we capture k8s api log file as well so if there were any issues on that end, we do capture them in the debug to help diagnose.
> NAS-127517 / 24.10 / Make sure we capture k8s_api.log in the debug

- ixdiagnose/artifacts/logs.py
We are logging netdata client errors to a separate file and this new log file should be grabbed in the debug as well to properly help diagnose.
> NAS-127111 / 24.10 / Grab netdata api log in debug

- ixdiagnose/artifacts/logs.py
git cherry-pick -x c519b7fb7db10a801af2768b4f4487417a18fb7b
git cherry-pick -x 1d43120bdec35cbe24793a87ea3fab63074f4d62
We are logging netdata client errors to a separate file and this new log file should be grabbed in the debug as well to properly help diagnose.
Original PR: https://github.com/truenas/ixdiagnose/pull/188
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127111
> NAS-127111 / 24.04.1 / Grab netdata api log in debug (by Qubad786)

- ixdiagnose/artifacts/base.py
- ixdiagnose/artifacts/logs.py
`ixdiagnose` was copying large unnecessary compressed files from the netdata logs directory, resulting in excessively large debug size.
Make sure we only retrieve latest files we are actually interested in wrt netdata as we can always exclusively ask for rest of them if need be in that case.
> NAS-128631 / 24.10 / Remove extra netdata files being retrieved

- ixdiagnose/artifacts/base.py
- ixdiagnose/artifacts/logs.py
`ixdiagnose` was copying large unnecessary compressed files from the netdata logs directory, resulting in excessively large debug size.
Make sure we only retrieve latest files we are actually interested in wrt netdata as we can always exclusively ask for rest of them if need be in that case.
Original PR: https://github.com/truenas/ixdiagnose/pull/190
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128631
> NAS-128631 / 24.04.1 / Remove extra netdata files being retrieved (by Qubad786)

- ixdiagnose/artifacts/items/file.py
In the previous implementation, all files in the directory were opened at once, which resulted in being out of fds if a directory had many files (e.g. job logs directory)
> NAS-128779 / 24.10 / Simplify `File` artifact implementation

- ixdiagnose/artifacts/items/file.py
In the previous implementation, all files in the directory were opened at once, which resulted in being out of fds if a directory had many files (e.g. job logs directory)
Original PR: https://github.com/truenas/ixdiagnose/pull/192
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128779
> NAS-128779 / 24.04.2 / Simplify `File` artifact implementation (by themylogin)

- ixdiagnose/plugins/nfs.py
Add several files from /proc/fs/nfsd
Add listing of /etc/nfs.conf.d (should be only local.conf) Refactor to standardize naming: '-' generally indicate path separator.
> NAS-129450 / 24.10 / Enhance information gathered for NFS

- ixdiagnose/plugins/nfs.py
Add several files from /proc/fs/nfsd
Add listing of /etc/nfs.conf.d (should be only local.conf) Refactor to standardize naming: '-' generally indicate path separator.
Original PR: https://github.com/truenas/ixdiagnose/pull/199
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129450
> NAS-129450 / 24.04.2 / Enhance information gathered for NFS (by mgrimesix)

- ixdiagnose/plugins/vm.py
Add iommu group directory tree in debug to capture how the iommu groups are laid out to better help in debugging issues related to passthrough.
> NAS-129825 / 24.10 / Capture iommu groups directory tree in debug

- ixdiagnose/plugins/audit.py
- ixdiagnose/plugins/factory.py
This commit adds the following information to the debugs we collect
1. Basic audit configuration (retention period, quota, space used, etc)
2. Audit query of recent middleware method calls. List of 100 most recent audited configuration changes on the NAS. This should help support triage changes users made that may be to blame for an issue encountered.
> NAS-130454 / 24.10 / Add audit details to debug

- ixdiagnose/plugins/iscsi.py
- ixdiagnose/plugins/metrics/__init__.py
- ixdiagnose/plugins/metrics/file.py
- ixdiagnose/test/pytest/unit/metrics/assets/redacted_file_metric_scst_input.txt
- ixdiagnose/test/pytest/unit/metrics/assets/redacted_file_metric_scst_output.txt
- ixdiagnose/test/pytest/unit/metrics/test_redacted_file_metric.py
- ixdiagnose/test/pytest/unit/utils.py
Add `RedactedFileMetric` and use `redact_chap_passwords` callback to redact iSCSI CHAP secrets.
This will replace the secrets in the copy of _/etc/scst.conf_.
Original PR: https://github.com/truenas/ixdiagnose/pull/211
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130771
> NAS-130771 / 24.10-RC.1 / Add RedactedFileMetric and use to redact iSCSI CHAP secrets (by bmeagherix)

- ixdiagnose/artifacts/logs.py
https://github.com/truenas/truenas_verify/pull/1
> NAS-130590 / 25.04 / add truenas_verify.log

- ixdiagnose/plugins/zfs.py
We use `zpool.status` internally in middleware when listing disks available, but we are not capturing what information we have parsed out from it in the debug and that has been added.
> NAS-131668 / 25.04 / Grab serialized zpool status output in debug

- ixdiagnose/plugins/zfs.py
We use `zpool.status` internally in middleware when listing disks available, but we are not capturing what information we have parsed out from it in the debug and that has been added.
Original PR: https://github.com/truenas/ixdiagnose/pull/227
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131668
> NAS-131668 / 24.10.0 / Grab serialized zpool status output in debug (by Qubad786)

- ixdiagnose/plugins/zfs.py
The support team has noticed that we're not capturing zvol information in our debugs. This adds that information but adds it to its own file `zvol_config.txt`
> NAS-132010 / 25.04 / add zvols to zvol_config.txt

- ixdiagnose/plugins/zfs.py
The support team has noticed that we're not capturing zvol information in our debugs. This adds that information but adds it to its own file `zvol_config.txt`
Original PR: https://github.com/truenas/ixdiagnose/pull/229
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132010
> NAS-132010 / 24.10.0 / add zvols to zvol_config.txt (by yocalebo)

- ixdiagnose/plugins/zfs.py
The support team has noticed that we're not capturing zvol information in our debugs. This adds that information but adds it to its own file `zvol_config.txt`
Original PR: https://github.com/truenas/ixdiagnose/pull/229
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132010
> NAS-132010 / 24.10.1 / add zvols to zvol_config.txt (by yocalebo)

- ixdiagnose/plugins/hardware.py
Simple omission that exists in CORE debug but not in SCALE debug.
Original PR: https://github.com/truenas/ixdiagnose/pull/234
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132049
Original PR: https://github.com/truenas/ixdiagnose/pull/235
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132049
> NAS-132049 / 24.10.0.1 / add ixnvdimm output to debug (by yocalebo) (by bugclerk)

- ixdiagnose/plugins/hardware.py
Simple omission that exists in CORE debug but not in SCALE debug.
Original PR: https://github.com/truenas/ixdiagnose/pull/234
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132049
Original PR: https://github.com/truenas/ixdiagnose/pull/235
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132049
Original PR: https://github.com/truenas/ixdiagnose/pull/236
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132049
> NAS-132049 / 24.04.2.4 / add ixnvdimm output to debug (by yocalebo) (by bugclerk) (by bugclerk)

- ixdiagnose/plugins/hardware.py
Adds the virtualization information provided in https://github.com/truenas/middleware/pull/14886
Original PR: https://github.com/truenas/ixdiagnose/pull/238
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132314
> NAS-132314 / 24.10.1 / add virtualization info (by yocalebo)

- ixdiagnose/plugins/hardware.py
Noticed while working on an unrelated PR. Noticed ixnvdimm output looked like this
```
==================== /dev/nmem0 ====================Module:
vendor: ce01 device: 4e39 revision: 34
subvendor: c180 subdevice: 4331 subrevision: 01
serial: 10680000
```
With the fix in place, it looks like this
```
==================== /dev/nmem0 ====================
Module:
vendor: ce01 device: 4e39 revision: 34
subvendor: c180 subdevice: 4331 subrevision: 01
serial: 10680000
> NAS-132315 / 25.04 / fix minor cosmetic ixnvdimm output

- ixdiagnose/plugins/hardware.py
Noticed while working on an unrelated PR. Noticed ixnvdimm output looked like this
```
==================== /dev/nmem0 ====================Module:
vendor: ce01 device: 4e39 revision: 34
subvendor: c180 subdevice: 4331 subrevision: 01
serial: 10680000
```
With the fix in place, it looks like this
```
==================== /dev/nmem0 ====================
Module:
vendor: ce01 device: 4e39 revision: 34
subvendor: c180 subdevice: 4331 subrevision: 01
serial: 10680000
Original PR: https://github.com/truenas/ixdiagnose/pull/240
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132315
> NAS-132315 / 24.10.1 / fix minor cosmetic ixnvdimm output (by yocalebo)

- ixdiagnose/plugins/hardware.py
- ixdiagnose/plugins/network.py
Noticed these were missing.
(Currently WIP because want to do further testing.)
> NAS-132534 / 25.04 / Add jbof and rdma

- ixdiagnose/plugins/ldap.py
LDAP attempts to collect configuration for nslcd, but nslcd has been replaced with sssd.
This PR removes nslcd from LDAP data collection and replaces it with sssd.
Exclude password fields.
Manual test showed password field was excluded.
> NAS-132562 / 25.04 / Update LDAP config collection for sssd

- ixdiagnose/plugins/ldap.py
LDAP attempts to collect configuration for nslcd, but nslcd has been replaced with sssd.
This PR removes nslcd from LDAP data collection and replaces it with sssd.
Exclude password fields.
Manual test showed password field was excluded.
Original PR: https://github.com/truenas/ixdiagnose/pull/245
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132562
> NAS-132562 / 24.10.1 / Update LDAP config collection for sssd (by mgrimesix)

- ixdiagnose/plugins/factory.py
- ixdiagnose/plugins/snmp.py
SNMP is missing from the diagnostic.
This PR adds SNMP configuration and associated files to a diagnostic.
> NAS-132555 / 25.04 / Include snmp in plugins diagnostic.

- ixdiagnose/plugins/factory.py
- ixdiagnose/plugins/nvme.py
- ixdiagnose/plugins/smart.py
We have a severe lack of nvme information being captured in the debug. This remedies that problem based on input from platform team. This also stops calling `smartctl -a` since the command barfs a line in the output stating it's "legacy" and we should use `-x` instead.
> NAS-132548 / 25.04 / Add NVME plugin

- ixdiagnose/plugins/factory.py
- ixdiagnose/plugins/nvme.py
- ixdiagnose/plugins/smart.py
We have a severe lack of nvme information being captured in the debug. This remedies that problem based on input from platform team. This also stops calling `smartctl -a` since the command barfs a line in the output stating it's "legacy" and we should use `-x` instead.
Original PR: https://github.com/truenas/ixdiagnose/pull/248
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132548
> NAS-132548 / 24.10.1 / Add NVME plugin (by yocalebo)

- ixdiagnose/plugins/factory.py
- ixdiagnose/plugins/snmp.py
SNMP is missing from the diagnostic.
This PR adds SNMP configuration and associated files to a diagnostic.
Original PR: https://github.com/truenas/ixdiagnose/pull/244
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132555
> NAS-132555 / 24.10.1 / Include snmp in plugins diagnostic. (by mgrimesix)

- ixdiagnose/plugins/zfs.py
If there are zvols, stderr is printed to and there will be no stdout. We'll crash on `output_lines[0]` with IndexError. Just handle the fact when there is no output.
> NAS-132940 / 25.04 / fix zvol output when there are no zvols

- ixdiagnose/plugins/zfs.py
If there are zvols, stderr is printed to and there will be no stdout. We'll crash on `output_lines[0]` with IndexError. Just handle the fact when there is no output.
Original PR: https://github.com/truenas/ixdiagnose/pull/250
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132940
> NAS-132940 / 24.10.2 / fix zvol output when there are no zvols (by yocalebo)

- ixdiagnose/cli.py
- ixdiagnose/config.py
- ixdiagnose/plugins/audit.py
This PR adds the 100 most recent SYSTEM event audit entries, a sha256 sum of `/conf/rootfs.mtree` and an `aureport`.
All will be contained in `plugins/audit`.
Also,
Changed default timeout from 20 to 30 seconds.
The addition of verify can take longer than 20 seconds on VMs with few cores or weak machines.
> NAS-133969 / 25.10 / Include audit SYSTEM events

- ixdiagnose/plugins/virt.py
This commit removes raw keys from the virt instance output in debugs since it may leak sensitive information.
> NAS-134761 / 25.10 / Redact virt instance output

- ixdiagnose/plugins/virt.py
This commit removes raw keys from the virt instance output in debugs since it may leak sensitive information.
Original PR: https://github.com/truenas/ixdiagnose/pull/271
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134761
> NAS-134761 / 25.04.0 / Redact virt instance output (by anodos325)

- ixdiagnose/plugins/audit.py
We collect the 100 most recent `SYSTEM` audit messages.    The large number of `SERVICE_START` and `SERVICE_STOP` messages easily fills the 100 message allocation.  This results in missing potentially important and interesting `SYSTEM` messages.
This PR adds a filter to the collection of `SYSTEM` audit messages to ignore `SERVICE_START` and `SERVICE_STOP` messages.
This PR has companion PR in `middleware` and `audit_rules`.
> NAS-134820 / 25.10 / Filter out SERVICE_START and SERVICE_STOP audit messages

- ixdiagnose/plugins/audit.py
We collect the 100 most recent `SYSTEM` audit messages.    The large number of `SERVICE_START` and `SERVICE_STOP` messages easily fills the 100 message allocation.  This results in missing potentially important and interesting `SYSTEM` messages.
This PR adds a filter to the collection of `SYSTEM` audit messages to ignore `SERVICE_START` and `SERVICE_STOP` messages.
This PR has companion PR in `middleware` and `audit_rules`.
Original PR: https://github.com/truenas/ixdiagnose/pull/273
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134820
> NAS-134820 / 25.04.0 / Filter out SERVICE_START and SERVICE_STOP audit messages (by mgrimesix)

- ixdiagnose/plugins/factory.py
- ixdiagnose/plugins/fc.py
- ixdiagnose/plugins/prerequisites/__init__.py
- ixdiagnose/plugins/prerequisites/fc.py
Add Fibre Channel information to debug.
While _scst.conf_ will contain information about configured FC targets, it may be useful to have more **raw** data to debug any issues that arise.
> NAS-135138 / 25.10 / Add Fibre Channel information

- ixdiagnose/plugins/factory.py
- ixdiagnose/plugins/fc.py
- ixdiagnose/plugins/prerequisites/__init__.py
- ixdiagnose/plugins/prerequisites/fc.py
Add Fibre Channel information to debug.
While _scst.conf_ will contain information about configured FC targets, it may be useful to have more **raw** data to debug any issues that arise.
Original PR: https://github.com/truenas/ixdiagnose/pull/277
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135138
> NAS-135138 / 25.04.1 /Add Fibre Channel information

- ixdiagnose/plugins/factory.py
- ixdiagnose/plugins/nvmet.py
- ixdiagnose/utils/formatter.py
- Add nvmet information to debug
- Add `redact_keys` formatter, modelled on `remove_keys`
The latter is for when we want to keep information private, but still show that a setting was set (or not).
> NAS-135625 / 25.10 / Add nvmet information to debug

- ixdiagnose/plugins/system.py
This catches STIG, FIPS, and account policy settings
Original PR: https://github.com/truenas/ixdiagnose/pull/280
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135636
> NAS-135636 / 25.04.2 / Add system security config to debug (by anodos325)

- ixdiagnose/plugins/system.py
This catches STIG, FIPS, and account policy settings
Original PR: https://github.com/truenas/ixdiagnose/pull/280
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135636
> NAS-135636 / 25.04.1 / Add system security config to debug (by anodos325)

- ixdiagnose/artifacts/logs.py
```
root@fangtooth-hv-rc[~]# ls /var/log/sssd
ldap_child.log  sssd.log.2.gz  sssd_mcgipa.mcg.log       sssd_mcgipa.mcg.log.3.gz  sssd_nss.log.1     sssd_nss.log.4.gz  sssd_pac.log.2.gz  sssd_pam.log.1
sssd.log        sssd.log.3.gz  sssd_mcgipa.mcg.log.1     sssd_mcgipa.mcg.log.4.gz  sssd_nss.log.2.gz  sssd_pac.log       sssd_pac.log.3.gz  sssd_pam.log.2.gz
sssd.log.1      sssd.log.4.gz  sssd_mcgipa.mcg.log.2.gz  sssd_nss.log              sssd_nss.log.3.gz  sssd_pac.log.1     sssd_pam.log       sssd_pam.log.3.gz
root@fangtooth-hv-rc[~]#
root@fangtooth-hv-rc[~]#
root@fangtooth-hv-rc[~]# ixdiagnose artifact --debug-path=/root
Specified configuration for debug generation is
- timeout for debug generation: 30 seconds.
- debug path set to /root
Completed debug …
```
> NAS-135769 / 25.10 / Add sssd logs to artifacts.

- ixdiagnose/plugins/factory.py
- ixdiagnose/plugins/metrics/base.py
- ixdiagnose/plugins/metrics/file.py
- ixdiagnose/plugins/ssh.py
- ixdiagnose/test/pytest/unit/test_formatter/test_formatter.py
- ixdiagnose/utils/formatter.py
- ixdiagnose/utils/middleware.py
git cherry-pick -x 3e1d701caa4d3658c7e3383c0af8cbc2c50509df
git cherry-pick -x 852b6560d5c323fec47fad828dfabfbeda7e84a6
git cherry-pick -x c3be6392a1deb841cfa9f6af6cb55754be875396
git cherry-pick -x c180bf963ede8408d304e4d361c789fe82224347
git cherry-pick -x 606513e2ff16dbe6cf0ab4597d3f85d8ba8ad013
git cherry-pick -x 4a9e5cbb37ee227a93516f8cd3f61f7a8bbc0391
git cherry-pick -x a2d312d1b86b3e9d6234db05089b9e6a03ba0302
git cherry-pick -x 2443d8b6dee5652ae34e6a5154c430572a4bb34d
git cherry-pick -x 8b172d37c9808f3e837cae8f82757b85d46a391a
git cherry-pick -x …
> NAS-136068 / 25.04.2 / Add new SSH plugin to debugs (by creatorcary)

- ixdiagnose/plugins/fc.py
Support wanted to add additional Fibre Channel output, both as a live tool on the system and also to debugs.
> NAS-135912 / 25.10 / Add fcdump.py output to debug

- ixdiagnose/plugins/system.py
There is a possibility if the timing of tasks gathering is just right that sensitive information may leak into debugs. Since there is no practical way to redact stack info with 100% certainty we'll just accept the reduced ability to debug reported issues.
> NAS-136919 / 25.10 / Remove core.get_tasks from debug collection

- ixdiagnose/plugins/system.py
There is a possibility if the timing of tasks gathering is just right that sensitive information may leak into debugs. Since there is no practical way to redact stack info with 100% certainty we'll just accept the reduced ability to debug reported issues.
Original PR: https://github.com/truenas/ixdiagnose/pull/301
> NAS-136919 / 25.04.2.1 / Remove core.get_tasks from debug collection (by anodos325)

- ixdiagnose/plugins/system.py
There is a possibility if the timing of tasks gathering is just right that sensitive information may leak into debugs. Since there is no practical way to redact stack info with 100% certainty we'll just accept the reduced ability to debug reported issues.
Original PR: https://github.com/truenas/ixdiagnose/pull/301
> NAS-136919 / 24.10.2.4 / Remove core.get_tasks from debug collection (by anodos325)

- ixdiagnose/artifacts/crashdump.py
- ixdiagnose/artifacts/factory.py
- ixdiagnose/artifacts/items/glob.py
ACPI ERST is selected as the pstore backend by default, which dumps kernel dmesg buffer to ACPI ERST tables that are later concatenated by systemd. We have ACPI ERST tables available on almost all enterprise platforms, and panic dumps are already logged to `/var/lib/systemd/pstore/` by the systemd-pstore service. This change integrates the crash dumps into ixdiagnose.
- The following is the structure of the generated crash dump.
```
$ tree artifacts/crashdump/
artifacts/crashdump/
├── pstore
│   ├── 7535166971441053699
│   │   └── dmesg.txt
│   └── 7535167727355297793
│       └── dmesg.txt
└── report.json
7 directories, 3 files
```
- Validated that the crashdump artifacts correctly updated after a panic.
- [Scale Build](http://jenkins.eng.ixsystems.net:8080/job/master/job/custom/1402/).
> NAS-136934 / 26.04 / Collect systemd pstore crash dumps in ixdiagnose

- ixdiagnose/artifacts/sys_parameters.py
Use the relative_to parameter introduced in PR #305 to create cleaner directory structure. `sysfs_parameters/sys/module/*/parameters/*` becomes `sysfs_parameters/*/parameters/*`.
> NAS-137047 / 26.04 / sysfs_parameters: Use relative_to for clean structure

- ixdiagnose/plugins/hardware.py
- ixdiagnose/plugins/prerequisites/__init__.py
- ixdiagnose/plugins/prerequisites/jbof.py
Add `jbof_view` to `hardware` plugin - gated by `JBOFPrerequisite`.
WIP pending underlying jbof_view.py script being added to build (middleware PR).
> NAS-136827 / 26.04 / Add jbof_view to hardware plugin

- ixdiagnose/plugins/hardware.py
- ixdiagnose/plugins/prerequisites/__init__.py
- ixdiagnose/plugins/prerequisites/jbof.py
Add `jbof_view` to `hardware` plugin - gated by `JBOFPrerequisite`.
WIP pending underlying jbof_view.py script being added to build (middleware PR).
Original PR: https://github.com/truenas/ixdiagnose/pull/312
> NAS-136827 / 25.10-RC.1 / Add jbof_view to hardware plugin (by bmeagherix)
