ixdiagnose/test/pytest/integration/test_artifacts.py, ixdiagnose/test/pytest/integration/test_plugins.py
Integration tests have been added for validating event configuration which will be used in middleware to get realtime job progress of the debug generation.
=> Integration tests for event callbacks in plugins/artifacts

ixdiagnose/test/pytest/unit/run/test_debug.py
Unit tests have been added to account for various validation in place for generating a debug to make sure the workflow works as intended.
=> Unit tests for compression validation logic

ixdiagnose/test/pytest/unit/configuration/test_config.py
Unit tests for configuration extension have been added which cover:
1. Validating schema of the configuration
2. Confirm values have been updated successfully
=> Added unit tests for configuration extension

docs/artifacts/artfacts.md
- Language and grammar pass
- Clarified example definitions
- adjust headers
=> NAS-122226 / 23.10 / Docs review artifacts.md

ixdiagnose/plugin.py, ixdiagnose/plugins/clustering.py, ixdiagnose/plugins/factory.py
Gather basic configuration and state information for cluster nodes.
=> NAS-122952 / 23.10 / Gather clustering debug

ixdiagnose/plugins/factory.py, ixdiagnose/plugins/ftp.py, ixdiagnose/plugins/nfs.py
* Add support for FTP
* Update NFS to include systemctl status of gssproxy service
=> NAS-123135 / 23.10 / Update ixdiagnose to include FTP and gssproxy

ixdiagnose/plugins/factory.py, ixdiagnose/plugins/ipmi.py
We're not capturing IPMI info in the new debug so this adds that information.
=> NAS-123222 / 23.10 / add IPMI plugin to gather ipmi related info

ixdiagnose/plugins/cpu.py, ixdiagnose/plugins/factory.py
=> NAS-123197 / 23.10 / add cpu plugin and gather cpu ppin info

ixdiagnose/plugins/cronjob.py, ixdiagnose/plugins/factory.py
It was requested that we capture cronjobs in our debug.
=> NAS-123640 / 24.04 / Add cronjob plugin

ixdiagnose/plugins/cronjob.py, ixdiagnose/plugins/factory.py
It was requested that we capture cronjobs in our debug.
Original PR: https://github.com/truenas/ixdiagnose/pull/50
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123640
=> NAS-123640 / 23.10 / Add cronjob plugin (by Qubad786)

ixdiagnose/artifacts/logs.py
(cherry picked from commit ad1c1acd57dcf092a14e66df87402dc1a8b471f6)
=> add fenced.log to logs

ixdiagnose/plugins/system.py
Useful compiled/short version of system overview.
=> NAS-124270 / 24.04 / Add system.info

ixdiagnose/plugins/system.py
Useful compiled/short version of system overview.
Original PR: https://github.com/truenas/ixdiagnose/pull/72
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124270
=> NAS-124270 / 23.10 / Add system.info (by william-gr)

README.md
Added a concise README.md for improved code documentation.
=> NAS-124501 / 24.04 / Update README for ixdiagnose

README.md
Added a concise README.md for improved code documentation.
Original PR: https://github.com/truenas/ixdiagnose/pull/88
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124501
=> NAS-124501 / 23.10.0 / Update README for ixdiagnose (by Qubad786)

README.md
Added a concise README.md for improved code documentation.
Original PR: https://github.com/truenas/ixdiagnose/pull/88
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124501
=> NAS-124501 / 23.10.1 / Update README for ixdiagnose (by Qubad786)

ixdiagnose/artifacts/factory.py, ixdiagnose/artifacts/sys_parameters.py
It was requested that we retrieve sysfs module parameters in our debug for debugging purposes.
=> NAS-124597 / 24.04 / Collect sysfs modules parameters

ixdiagnose/plugins/vm.py
git cherry-pick -x aaf040b07825e1808d338b2d884dbdb5d3e0539d
git cherry-pick -x 9c61e49e0fda57ab59c9052c53e36b0375c77610
git cherry-pick -x 49402cdcec50a02eafbb6db175351ae420a86c70
git cherry-pick -x aab4e84c03db0d2aff8bc2abd9bb9b6e173ece2c
git cherry-pick -x cd8b179226ac2726d264e3c3cdc7e462a21a271a
git cherry-pick -x 43a1a93f01b8948ae597cef3c1c8e9aa04e0f118
Original PR: https://github.com/truenas/ixdiagnose/pull/107
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124772
=> NAS-124772 / 23.10.1 / Retrieve iommu groups information in debug (by sonicaj)

docs/artifacts/artifacts.md, docs/artifacts/items/items.md
This PR adds documentation for glob item type in [items doc](https://github.com/truenas/ixdiagnose/blob/master/docs/artifacts/items/items.md). 
The work was done in [this PR](https://github.com/truenas/ixdiagnose/pull/91).
=> NAS-125105 / 24.04 / Add docs for glob item type

ixdiagnose/plugins/containers.py, ixdiagnose/plugins/factory.py
Example output looks like:
```
[
{
"machine": "bookworm01",
"class": "container",
"service": "systemd-nspawn",
"os": "debian",
"version": "12",
"addresses": null
}
]
=> NAS-125734 / 24.04 / add Containers plugin

ixdiagnose/plugins/containers.py, ixdiagnose/plugins/factory.py
Example output looks like:
```
[
{
"machine": "bookworm01",
"class": "container",
"service": "systemd-nspawn",
"os": "debian",
"version": "12",
"addresses": null
}
]
```
Original PR: https://github.com/truenas/ixdiagnose/pull/131
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125734
=> NAS-125734 / 23.10.2 / add Containers plugin (by yocalebo)

ixdiagnose/plugins/system.py
Adding swap information in the debug so devs can see which disks are being used in swap to effectively determine/investigate bugs.
Example output:
```
❯ cat /root/debugs_new/ixdiagnose/plugins/system/swap_info.json
{
"swap_disks": [
"/dev/vdb1"
],
"error": null
}#  
```
=> NAS-125669 / 24.04 / Add swap configuration in system plugin

ixdiagnose/plugins/system.py
Adding swap information in the debug so devs can see which disks are being used in swap to effectively determine/investigate bugs.
Example output:
```
❯ cat /root/debugs_new/ixdiagnose/plugins/system/swap_info.json
{
"swap_disks": [
"/dev/vdb1"
],
"error": null
}#  
```
Original PR: https://github.com/truenas/ixdiagnose/pull/130
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125669
=> NAS-125669 / 23.10.2 / Add swap configuration in system plugin (by Qubad786)

ixdiagnose/plugins/factory.py, ixdiagnose/plugins/rbac.py
This commit adds new plugin to include privilege-related info in debug files.
=> NAS-125872 / 24.04 / Add plugin for privilege-related info

ixdiagnose/plugins/rbac.py
* Currently authenticated middleware sessions
* List of privileged local users.
=> NAS-125926 / 24.04 / Expand rbac-related debug information

ixdiagnose/plugins/active_directory.py
We were missing kerberos information here.
=> NAS-126889 / 24.10 / Add missing information to AD debug

ixdiagnose/plugins/system.py
=> NAS-127625 / 24.10 / `gather_update_failed` is no longer needed

ixdiagnose/plugins/factory.py, ixdiagnose/plugins/ups.py
PR adds a new plugin to include output of upsc command to debug files if ups service is running for better visibility of what's going on in their UPS parameters.
=> NAS-128135 / 24.10 / Add UPS plugin

ixdiagnose/plugins/system_state.py
Reverts truenas/ixdiagnose#183
=> NAS-128235 / 24.10 / Revert "NAS-128223 / 24.10 / add /data/update.failed"

ixdiagnose/artifacts/items/file.py
In the previous implementation, all files in the directory were opened at once, which resulted in being out of fds if a directory had many files (e.g. job logs directory)
Original PR: https://github.com/truenas/ixdiagnose/pull/192
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128779
=> NAS-128779 / 24.04.1 / Simplify `File` artifact implementation (by themylogin)

ixdiagnose/plugins/smart.py
This properly detects nvme devices via the T10 vendor string but also fixes the situation where we weren't passing `-d nvme` to the device if it was a proper nvme device (i.e. /dev/nvme*)
=> NAS-129281 / 24.10 / detect nvme devices via vendor string

ixdiagnose/plugins/iscsi.py, ixdiagnose/plugins/metrics/__init__.py, ixdiagnose/plugins/metrics/file.py, ixdiagnose/test/pytest/unit/metrics/assets/redacted_file_metric_scst_input.txt, ixdiagnose/test/pytest/unit/metrics/assets/redacted_file_metric_scst_output.txt, ixdiagnose/test/pytest/unit/metrics/test_redacted_file_metric.py, ixdiagnose/test/pytest/unit/utils.py
Add `RedactedFileMetric` and use `redact_chap_passwords` callback to redact iSCSI CHAP secrets.
This will replace the secrets in the copy of _/etc/scst.conf_.
=> NAS-130771 / 25.04 / Add RedactedFileMetric and use to redact iSCSI CHAP secrets

ixdiagnose/plugins/smb.py
Ensure that we don't populate NT password hash in the passdb output.
=> NAS-130778 / 25.04 / Redact passdb_list results

ixdiagnose/artifacts/logs.py
https://github.com/truenas/truenas_verify/pull/1
Original PR: https://github.com/truenas/ixdiagnose/pull/217
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130590
=> NAS-130590 / 24.10-RC.1 / add truenas_verify.log (by creatorcary)

ixdiagnose/test/pytest/unit/plugins/test_zfs.py
Fix failing zfs unit test in ixdiagnose.
=> NAS-132055 / 25.04 / Fix zfs get acl unit test

ixdiagnose/plugins/hardware.py
Simple omission that exists in CORE debug but not in SCALE debug.
=> NAS-132049 / 25.04 / add ixnvdimm output to debug

ixdiagnose/plugins/hardware.py
Adds the virtualization information provided in https://github.com/truenas/middleware/pull/14886
=> NAS-132314 / 25.04 / add virtualization info

ixdiagnose/plugins/hardware.py, ixdiagnose/plugins/network.py
Noticed these were missing.
Original PR: https://github.com/truenas/ixdiagnose/pull/242
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132534
=> NAS-132534 / 24.10.1 / Add jbof and rdma (by bmeagherix)

ixdiagnose/plugins/exceptions.py, ixdiagnose/plugins/factory.py
This adds explicit dumping ground for exceptions we're generating on TrueNAS.
=> NAS-133336 / 25.04 / Add structured exception data to debug

ixdiagnose/plugins/metrics/command.py, ixdiagnose/plugins/system_state.py, ixdiagnose/utils/command.py
Due to using `systemd-sysext`, we never modify files in `/usr` anymore.
=> NAS-133548 / 25.04 / Remove modified files whitelist in `/usr`

ixdiagnose/plugins/audit.py
Add truenas_verify run and log capture to the audit plugin.
=> NAS-133968 / 25.10 / Add truenas_verify data to audit plugin.

ixdiagnose/plugins/audit.py
Add truenas_verify run and log capture to the audit plugin.
Original PR: https://github.com/truenas/ixdiagnose/pull/264
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133968
=> NAS-133968 / 25.04-RC.1 / Add truenas_verify data to audit plugin. (by mgrimesix)

ixdiagnose/artifacts/logs.py, ixdiagnose/plugins/factory.py, ixdiagnose/plugins/virt.py
This commit adds basic debug info for incus.
=> NAS-134506 / 25.10 / Add ixdiagnose virt plugin

ixdiagnose/artifacts/logs.py, ixdiagnose/plugins/factory.py, ixdiagnose/plugins/virt.py
This commit adds basic debug info for incus.
Original PR: https://github.com/truenas/ixdiagnose/pull/268
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134506
=> NAS-134506 / 25.04-RC.1 / Add ixdiagnose virt plugin (by anodos325)

ixdiagnose/artifacts/logs.py, ixdiagnose/plugins/factory.py, ixdiagnose/plugins/virt.py
This commit adds basic debug info for incus.
=> NAS-134506 / 25.10 / Add ixdiagnose virt plugin (#268)

ixdiagnose/plugins/virt.py
The 25.04.0 release cycle exposed that we need full incus configuration for instances in order to properly triage tickets.
=> NAS-135737 / 25.10 / Add raw incus instance information

ixdiagnose/plugins/system.py
This catches STIG, FIPS, and account policy settings
=> NAS-135636 / 25.10 / Add system security config to debug

ixdiagnose/plugins/virt.py
The 25.04.0 release cycle exposed that we need full incus configuration for instances in order to properly triage tickets.
Original PR: https://github.com/truenas/ixdiagnose/pull/281
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135737
=> NAS-135737 / 25.04.1 / Add raw incus instance information (by anodos325)

ixdiagnose/plugins/metrics/base.py, ixdiagnose/plugins/metrics/python.py, ixdiagnose/plugins/network.py, ixdiagnose/utils/middleware.py
Run `ethtool -m <interface_name>` for every network interface including RDMA links.
Also fix a few type hints.
=> NAS-135911 / 25.10 / Add output of `ethtool -m` to network plugin

ixdiagnose/plugins/metrics/base.py, ixdiagnose/plugins/metrics/python.py, ixdiagnose/plugins/network.py, ixdiagnose/utils/middleware.py
Run `ethtool -m <interface_name>` for every network interface including RDMA links.
Also fix a few type hints.
Original PR: https://github.com/truenas/ixdiagnose/pull/289
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135911
=> NAS-135911 / 25.04.2 / Add output of `ethtool -m` to network plugin (by creatorcary)

ixdiagnose/artifacts/logs.py, ixdiagnose/plugins/factory.py, ixdiagnose/plugins/vm.py
This reverts commit fade96547027ed7b62590e883a86811be3734f8a.
Original PR: https://github.com/truenas/ixdiagnose/pull/299
=> NAS-136801 / 25.04.2 / Revert "Remove legacy VM usages from ixdiagnose" (by Qubad786)
